---
- name: Installer python3-docker et awscli
  ansible.builtin.apt:
    name:
      - awscli 
      - python3-docker
    state: present
    update_cache: true
    
- name: Initialisation du docker swarm manager
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ ansible_host }}"
  register: swarm_info

- name: Supprimer le stack si il existe déjà
  community.docker.docker_stack:
    name: rpn
    state: absent
  ignore_errors: true
  tags: 
    - rpn